# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
#- {name: 'AI and the Environment',  url: 'AI'}
#- {name: 'Global Goals Experience', url: 'Global'}
#- {name: 'Tailored',       url: 'Tailored'}
#- {name: 'Documentation',      url: 'documentation'}
- {name: 'Home',              url: 'home'}
- {name: 'Our Toolkits',  url: 'Toolkits'}
- {name: 'Our Partners',  url: 'Partners'}
- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
#- {icon: 'envelope', link:   'mailto:j.c.walton@sussex.ac.uk'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

related_posts: 'You may also enjoy...'

#post_date_prefix: 'Written on'