# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'What We Do',              url: 'What-We-Do'}
- {name: 'Our Toolkits',  url: 'Toolkits'}
- {name: 'AI Workshop',  url: 'AI-Workshop'}
- {name: 'Global Goals Experience', url: 'Global-Goals-Experience'}
- {name: 'Tailored',       url: 'Tailored-Outcomes'}
- {name: 'Our Partners',  url: 'Partners'}
- {name: 'Contact',            url: 'Contact'}
#- {name: 'Documentation',      url: 'Documentation'}


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
#- {icon: 'envelope', link:   'mailto:j.c.walton@sussex.ac.uk'}

# Customize site text
pagination:
  #next_page: 'Newer'
  #previous_page: 'Older'

#post_date_prefix: 'Written on'